<?php
  
  require($_SERVER['DOCUMENT_ROOT'] . '/bitrix/header.php');
  /** @var CMain $APPLICATION */
  $APPLICATION->SetTitle("Услуги");
  
  $arDefaultUrlTemplates404 = [
    'list' => 'index.php',
    'element' => '#ELEMENT_ID#.php',
  ];
?><?
  $APPLICATION->IncludeComponent(
    "bitrix:news.detail",
    "services_about",
    array(
      "ACTIVE_DATE_FORMAT" => "d.m.Y",
      "ADD_ELEMENT_CHAIN" => "N",
      "ADD_SECTIONS_CHAIN" => "N",
      "AJAX_MODE" => "N",
      "AJAX_OPTION_ADDITIONAL" => "",
      "AJAX_OPTION_HISTORY" => "N",
      "AJAX_OPTION_JUMP" => "N",
      "AJAX_OPTION_STYLE" => "Y",
      "BROWSER_TITLE" => "-",
      "CACHE_GROUPS" => "N",
      "CACHE_TIME" => "36000000",
      "CACHE_TYPE" => "A",
      "CHECK_DATES" => "Y",
      "COMPONENT_TEMPLATE" => "services_about",
      "DETAIL_URL" => "",
      "DISPLAY_BOTTOM_PAGER" => "N",
      "DISPLAY_DATE" => "N",
      "DISPLAY_NAME" => "N",
      "DISPLAY_PICTURE" => "N",
      "DISPLAY_PREVIEW_TEXT" => "N",
      "DISPLAY_TOP_PAGER" => "N",
      "ELEMENT_CODE" => "",
      "ELEMENT_ID" => "19",
      "FIELD_CODE" => array(
        0 => "ID",
        1 => "CODE",
        2 => "XML_ID",
        3 => "NAME",
        4 => "TAGS",
        5 => "SORT",
        6 => "PREVIEW_TEXT",
        7 => "PREVIEW_PICTURE",
        8 => "DETAIL_TEXT",
        9 => "DETAIL_PICTURE",
        10 => "DATE_ACTIVE_FROM",
        11 => "ACTIVE_FROM",
        12 => "DATE_ACTIVE_TO",
        13 => "ACTIVE_TO",
        14 => "SHOW_COUNTER",
        15 => "SHOW_COUNTER_START",
        16 => "IBLOCK_TYPE_ID",
        17 => "IBLOCK_ID",
        18 => "IBLOCK_CODE",
        19 => "IBLOCK_NAME",
        20 => "IBLOCK_EXTERNAL_ID",
        21 => "DATE_CREATE",
        22 => "CREATED_BY",
        23 => "CREATED_USER_NAME",
        24 => "TIMESTAMP_X",
        25 => "MODIFIED_BY",
        26 => "USER_NAME",
        27 => "",
      ),
      "IBLOCK_ID" => "6",
      "IBLOCK_TYPE" => "Content",
      "IBLOCK_URL" => "",
      "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
      "MESSAGE_404" => "",
      "META_DESCRIPTION" => "-",
      "META_KEYWORDS" => "-",
      "PAGER_BASE_LINK_ENABLE" => "N",
      "PAGER_SHOW_ALL" => "N",
      "PAGER_TEMPLATE" => ".default",
      "PAGER_TITLE" => "Страница",
      "PROPERTY_CODE" => array(
        0 => "title",
        1 => "details",
        2 => "skills",
        3 => "",
      ),
      "SET_BROWSER_TITLE" => "Y",
      "SET_CANONICAL_URL" => "N",
      "SET_LAST_MODIFIED" => "N",
      "SET_META_DESCRIPTION" => "Y",
      "SET_META_KEYWORDS" => "Y",
      "SET_STATUS_404" => "N",
      "SET_TITLE" => "N",
      "SHOW_404" => "N",
      "STRICT_SECTION_CHECK" => "N",
      "USE_PERMISSIONS" => "N",
      "USE_SHARE" => "N"
    )
  ); ?><?
  $APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "main_activities",
    array(
      "ACTIVE_DATE_FORMAT" => "d.m.Y",
      "ADD_SECTIONS_CHAIN" => "N",
      "AJAX_MODE" => "N",
      "AJAX_OPTION_ADDITIONAL" => "",
      "AJAX_OPTION_HISTORY" => "N",
      "AJAX_OPTION_JUMP" => "N",
      "AJAX_OPTION_STYLE" => "Y",
      "CACHE_FILTER" => "N",
      "CACHE_GROUPS" => "N",
      "CACHE_TIME" => "36000000",
      "CACHE_TYPE" => "A",
      "CHECK_DATES" => "Y",
      "DETAIL_URL" => "",
      "DISPLAY_BOTTOM_PAGER" => "N",
      "DISPLAY_DATE" => "N",
      "DISPLAY_NAME" => "N",
      "DISPLAY_PICTURE" => "N",
      "DISPLAY_PREVIEW_TEXT" => "N",
      "DISPLAY_TOP_PAGER" => "N",
      "FIELD_CODE" => array(
        "ID",
        "CODE",
        "XML_ID",
        "NAME",
        "SORT",
        "PREVIEW_TEXT",
        "DETAIL_TEXT",
        "DETAIL_PICTURE",
        ""
      ),
      "FILTER_NAME" => "",
      "HIDE_LINK_WHEN_NO_DETAIL" => "N",
      "IBLOCK_ID" => "2",
      "IBLOCK_TYPE" => "Content",
      "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
      "INCLUDE_SUBSECTIONS" => "N",
      "MESSAGE_404" => "",
      "NEWS_COUNT" => "6",
      "PAGER_BASE_LINK_ENABLE" => "N",
      "PAGER_DESC_NUMBERING" => "N",
      "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
      "PAGER_SHOW_ALL" => "N",
      "PAGER_SHOW_ALWAYS" => "N",
      "PAGER_TEMPLATE" => ".default",
      "PAGER_TITLE" => "Новости",
      "PARENT_SECTION" => "",
      "PARENT_SECTION_CODE" => "",
      "PREVIEW_TRUNCATE_LEN" => "",
      "PROPERTY_CODE" => array("", ""),
      "SET_BROWSER_TITLE" => "N",
      "SET_LAST_MODIFIED" => "N",
      "SET_META_DESCRIPTION" => "N",
      "SET_META_KEYWORDS" => "N",
      "SET_STATUS_404" => "N",
      "SET_TITLE" => "N",
      "SHOW_404" => "N",
      "SORT_BY1" => "ID",
      "SORT_BY2" => "SORT",
      "SORT_ORDER1" => "ASC",
      "SORT_ORDER2" => "ASC",
      "STRICT_SECTION_CHECK" => "N"
    )
  ); ?><?
  $APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "prices",
    array(
      "ACTIVE_DATE_FORMAT" => "j F Y",
      "ADD_SECTIONS_CHAIN" => "N",
      "AJAX_MODE" => "N",
      "AJAX_OPTION_ADDITIONAL" => "",
      "AJAX_OPTION_HISTORY" => "N",
      "AJAX_OPTION_JUMP" => "N",
      "AJAX_OPTION_STYLE" => "Y",
      "CACHE_FILTER" => "N",
      "CACHE_GROUPS" => "N",
      "CACHE_TIME" => "36000000",
      "CACHE_TYPE" => "A",
      "CHECK_DATES" => "Y",
      "DETAIL_URL" => "",
      "DISPLAY_BOTTOM_PAGER" => "N",
      "DISPLAY_DATE" => "N",
      "DISPLAY_NAME" => "Y",
      "DISPLAY_PICTURE" => "N",
      "DISPLAY_PREVIEW_TEXT" => "Y",
      "DISPLAY_TOP_PAGER" => "N",
      "FIELD_CODE" => array(
        "CODE",
        "XML_ID",
        "NAME",
        "SORT",
        "PREVIEW_TEXT",
        "DETAIL_TEXT",
        ""
      ),
      "FILTER_NAME" => "",
      "HIDE_LINK_WHEN_NO_DETAIL" => "N",
      "IBLOCK_ID" => "7",
      "IBLOCK_TYPE" => "Content",
      "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
      "INCLUDE_SUBSECTIONS" => "Y",
      "MESSAGE_404" => "",
      "NEWS_COUNT" => "5",
      "PAGER_BASE_LINK_ENABLE" => "N",
      "PAGER_DESC_NUMBERING" => "N",
      "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
      "PAGER_SHOW_ALL" => "N",
      "PAGER_SHOW_ALWAYS" => "N",
      "PAGER_TEMPLATE" => ".default",
      "PAGER_TITLE" => "Новости",
      "PARENT_SECTION" => "",
      "PARENT_SECTION_CODE" => "",
      "PREVIEW_TRUNCATE_LEN" => "",
      "PROPERTY_CODE" => array("attributes", ""),
      "SET_BROWSER_TITLE" => "N",
      "SET_LAST_MODIFIED" => "N",
      "SET_META_DESCRIPTION" => "N",
      "SET_META_KEYWORDS" => "N",
      "SET_STATUS_404" => "N",
      "SET_TITLE" => "N",
      "SHOW_404" => "N",
      "SORT_BY1" => "SORT",
      "SORT_BY2" => "SORT",
      "SORT_ORDER1" => "ASC",
      "SORT_ORDER2" => "ASC",
      "STRICT_SECTION_CHECK" => "N"
    )
  ); ?><?php
  require($_SERVER['DOCUMENT_ROOT'] . '/bitrix/footer.php');
?>
