<?
  
  require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
  /** @var CMain $APPLICATION */
  $APPLICATION->SetTitle("Интернет магазин");
  $APPLICATION->AddChainItem(
    $APPLICATION->GetTitle()
  );
?><?
  $APPLICATION->IncludeComponent(
    "bitrix:news.detail",
    "services_lending_post",
    array(
      "ACTIVE_DATE_FORMAT" => "d.m.Y",
      "ADD_ELEMENT_CHAIN" => "N",
      "ADD_SECTIONS_CHAIN" => "N",
      "AJAX_MODE" => "N",
      "AJAX_OPTION_ADDITIONAL" => "",
      "AJAX_OPTION_HISTORY" => "N",
      "AJAX_OPTION_JUMP" => "N",
      "AJAX_OPTION_STYLE" => "Y",
      "BROWSER_TITLE" => "-",
      "CACHE_GROUPS" => "N",
      "CACHE_TIME" => "36000000",
      "CACHE_TYPE" => "A",
      "CHECK_DATES" => "Y",
      "DETAIL_URL" => "",
      "DISPLAY_BOTTOM_PAGER" => "N",
      "DISPLAY_DATE" => "N",
      "DISPLAY_NAME" => "Y",
      "DISPLAY_PICTURE" => "Y",
      "DISPLAY_PREVIEW_TEXT" => "N",
      "DISPLAY_TOP_PAGER" => "N",
      "ELEMENT_CODE" => "",
      "ELEMENT_ID" => "29",
      "FIELD_CODE" => array("NAME", "DETAIL_TEXT", "DETAIL_PICTURE", ""),
      "IBLOCK_ID" => "8",
      "IBLOCK_TYPE" => "Content",
      "IBLOCK_URL" => "",
      "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
      "MESSAGE_404" => "",
      "META_DESCRIPTION" => "-",
      "META_KEYWORDS" => "-",
      "PAGER_BASE_LINK_ENABLE" => "N",
      "PAGER_SHOW_ALL" => "N",
      "PAGER_TEMPLATE" => ".default",
      "PAGER_TITLE" => "Страница",
      "PROPERTY_CODE" => array("", ""),
      "SET_BROWSER_TITLE" => "N",
      "SET_CANONICAL_URL" => "N",
      "SET_LAST_MODIFIED" => "N",
      "SET_META_DESCRIPTION" => "N",
      "SET_META_KEYWORDS" => "N",
      "SET_STATUS_404" => "N",
      "SET_TITLE" => "N",
      "SHOW_404" => "N",
      "STRICT_SECTION_CHECK" => "N",
      "USE_PERMISSIONS" => "N",
      "USE_SHARE" => "N"
    )
  ); ?><?
  $APPLICATION->IncludeComponent(
    "bitrix:news.detail",
    "services_faq",
    array(
      "ACTIVE_DATE_FORMAT" => "d.m.Y",
      "ADD_ELEMENT_CHAIN" => "N",
      "ADD_SECTIONS_CHAIN" => "N",
      "AJAX_MODE" => "N",
      "AJAX_OPTION_ADDITIONAL" => "",
      "AJAX_OPTION_HISTORY" => "N",
      "AJAX_OPTION_JUMP" => "N",
      "AJAX_OPTION_STYLE" => "Y",
      "BROWSER_TITLE" => "-",
      "CACHE_GROUPS" => "N",
      "CACHE_TIME" => "36000000",
      "CACHE_TYPE" => "A",
      "CHECK_DATES" => "Y",
      "DETAIL_URL" => "",
      "DISPLAY_BOTTOM_PAGER" => "N",
      "DISPLAY_DATE" => "N",
      "DISPLAY_NAME" => "Y",
      "DISPLAY_PICTURE" => "N",
      "DISPLAY_PREVIEW_TEXT" => "N",
      "DISPLAY_TOP_PAGER" => "N",
      "ELEMENT_CODE" => "",
      "ELEMENT_ID" => "30",
      "FIELD_CODE" => array("ID", "CODE", "XML_ID", "NAME", ""),
      "IBLOCK_ID" => "9",
      "IBLOCK_TYPE" => "Content",
      "IBLOCK_URL" => "",
      "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
      "MESSAGE_404" => "",
      "META_DESCRIPTION" => "-",
      "META_KEYWORDS" => "-",
      "PAGER_BASE_LINK_ENABLE" => "N",
      "PAGER_SHOW_ALL" => "N",
      "PAGER_TEMPLATE" => ".default",
      "PAGER_TITLE" => "Страница",
      "PROPERTY_CODE" => array("faq", "development_stages", ""),
      "SET_BROWSER_TITLE" => "N",
      "SET_CANONICAL_URL" => "N",
      "SET_LAST_MODIFIED" => "N",
      "SET_META_DESCRIPTION" => "N",
      "SET_META_KEYWORDS" => "N",
      "SET_STATUS_404" => "N",
      "SET_TITLE" => "N",
      "SHOW_404" => "N",
      "STRICT_SECTION_CHECK" => "N",
      "USE_PERMISSIONS" => "N",
      "USE_SHARE" => "N"
    )
  ); ?><?
  require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>
